#Instala a versão mais atual do CentOS e dá um nome
FROM centos:lastest AS centOS_crontab_interno

LABEL maintainer="Valdemir"

#Atualiza os pacotes prévios
RUN yum check-update && yum -y upgrade

#instala pacotes necessários do crontab
RUN yum install cronie

#agora seta o fuso horário do Nordeste com um link simbólico ;D

CMD ["rm", "-rf", "/etc/localtime"] 

CMD ["ln", "-s", "/usr/share/zoneinfo/Brazil/DeNoronha /etc/localtime"]

#Cria o arquivo do crontab e escreve a tarefa que será executada a cada 5 minutos

RUN echo "*/5 * * * * date >> /home/Documents/saida.txt" > /etc/cron.d/cron-teste

#apontar o arquivo para o daemon do crontab
CMD ["crontab", "/etc/cron.d/cron-teste"]

#Executa o programa do crontab pois não inicia automaticamente

ENTRYPOINT ["/usr/sbin/crond"]





